# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jamie/Documents/vscode/Drum-Rom-Designer-Casio-Rz-1-main

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jamie/Documents/vscode/Drum-Rom-Designer-Casio-Rz-1-main

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jamie/Documents/vscode/Drum-Rom-Designer-Casio-Rz-1-main/CMakeFiles /home/jamie/Documents/vscode/Drum-Rom-Designer-Casio-Rz-1-main//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jamie/Documents/vscode/Drum-Rom-Designer-Casio-Rz-1-main/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named drumrom_synth

# Build rule for target.
drumrom_synth: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 drumrom_synth
.PHONY : drumrom_synth

# fast build rule for target.
drumrom_synth/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/build
.PHONY : drumrom_synth/fast

#=============================================================================
# Target rules for targets named imgui_lib

# Build rule for target.
imgui_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui_lib
.PHONY : imgui_lib

# fast build rule for target.
imgui_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/build
.PHONY : imgui_lib/fast

#=============================================================================
# Target rules for targets named rtmidi_lib

# Build rule for target.
rtmidi_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rtmidi_lib
.PHONY : rtmidi_lib

# fast build rule for target.
rtmidi_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtmidi_lib.dir/build.make CMakeFiles/rtmidi_lib.dir/build
.PHONY : rtmidi_lib/fast

#=============================================================================
# Target rules for targets named drumrom_gui

# Build rule for target.
drumrom_gui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 drumrom_gui
.PHONY : drumrom_gui

# fast build rule for target.
drumrom_gui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/build
.PHONY : drumrom_gui/fast

#=============================================================================
# Target rules for targets named drumrom_build_bin

# Build rule for target.
drumrom_build_bin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 drumrom_build_bin
.PHONY : drumrom_build_bin

# fast build rule for target.
drumrom_build_bin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_build_bin.dir/build.make CMakeFiles/drumrom_build_bin.dir/build
.PHONY : drumrom_build_bin/fast

#=============================================================================
# Target rules for targets named synth_demo

# Build rule for target.
synth_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 synth_demo
.PHONY : synth_demo

# fast build rule for target.
synth_demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/synth_demo.dir/build.make CMakeFiles/synth_demo.dir/build
.PHONY : synth_demo/fast

#=============================================================================
# Target rules for targets named rtmidi

# Build rule for target.
rtmidi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rtmidi
.PHONY : rtmidi

# fast build rule for target.
rtmidi/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/rtmidi.dir/build.make _deps/rtmidi-build/CMakeFiles/rtmidi.dir/build
.PHONY : rtmidi/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/Experimental.dir/build.make _deps/rtmidi-build/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/Nightly.dir/build.make _deps/rtmidi-build/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/Continuous.dir/build.make _deps/rtmidi-build/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/NightlyMemoryCheck.dir/build.make _deps/rtmidi-build/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/NightlyStart.dir/build.make _deps/rtmidi-build/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/NightlyUpdate.dir/build.make _deps/rtmidi-build/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/NightlyConfigure.dir/build.make _deps/rtmidi-build/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/NightlyBuild.dir/build.make _deps/rtmidi-build/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/NightlyTest.dir/build.make _deps/rtmidi-build/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/NightlyCoverage.dir/build.make _deps/rtmidi-build/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/NightlyMemCheck.dir/build.make _deps/rtmidi-build/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/NightlySubmit.dir/build.make _deps/rtmidi-build/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/ExperimentalStart.dir/build.make _deps/rtmidi-build/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/ExperimentalUpdate.dir/build.make _deps/rtmidi-build/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/ExperimentalConfigure.dir/build.make _deps/rtmidi-build/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/ExperimentalBuild.dir/build.make _deps/rtmidi-build/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/ExperimentalTest.dir/build.make _deps/rtmidi-build/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/ExperimentalCoverage.dir/build.make _deps/rtmidi-build/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/ExperimentalMemCheck.dir/build.make _deps/rtmidi-build/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/ExperimentalSubmit.dir/build.make _deps/rtmidi-build/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/ContinuousStart.dir/build.make _deps/rtmidi-build/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/ContinuousUpdate.dir/build.make _deps/rtmidi-build/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/ContinuousConfigure.dir/build.make _deps/rtmidi-build/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/ContinuousBuild.dir/build.make _deps/rtmidi-build/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/ContinuousTest.dir/build.make _deps/rtmidi-build/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/ContinuousCoverage.dir/build.make _deps/rtmidi-build/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/ContinuousMemCheck.dir/build.make _deps/rtmidi-build/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/ContinuousSubmit.dir/build.make _deps/rtmidi-build/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named cmidiin

# Build rule for target.
cmidiin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cmidiin
.PHONY : cmidiin

# fast build rule for target.
cmidiin/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/cmidiin.dir/build.make _deps/rtmidi-build/CMakeFiles/cmidiin.dir/build
.PHONY : cmidiin/fast

#=============================================================================
# Target rules for targets named midiclock

# Build rule for target.
midiclock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 midiclock
.PHONY : midiclock

# fast build rule for target.
midiclock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/midiclock.dir/build.make _deps/rtmidi-build/CMakeFiles/midiclock.dir/build
.PHONY : midiclock/fast

#=============================================================================
# Target rules for targets named midiout

# Build rule for target.
midiout: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 midiout
.PHONY : midiout

# fast build rule for target.
midiout/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/midiout.dir/build.make _deps/rtmidi-build/CMakeFiles/midiout.dir/build
.PHONY : midiout/fast

#=============================================================================
# Target rules for targets named midiprobe

# Build rule for target.
midiprobe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 midiprobe
.PHONY : midiprobe

# fast build rule for target.
midiprobe/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/midiprobe.dir/build.make _deps/rtmidi-build/CMakeFiles/midiprobe.dir/build
.PHONY : midiprobe/fast

#=============================================================================
# Target rules for targets named qmidiin

# Build rule for target.
qmidiin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qmidiin
.PHONY : qmidiin

# fast build rule for target.
qmidiin/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/qmidiin.dir/build.make _deps/rtmidi-build/CMakeFiles/qmidiin.dir/build
.PHONY : qmidiin/fast

#=============================================================================
# Target rules for targets named sysextest

# Build rule for target.
sysextest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sysextest
.PHONY : sysextest

# fast build rule for target.
sysextest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/sysextest.dir/build.make _deps/rtmidi-build/CMakeFiles/sysextest.dir/build
.PHONY : sysextest/fast

#=============================================================================
# Target rules for targets named apinames

# Build rule for target.
apinames: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 apinames
.PHONY : apinames

# fast build rule for target.
apinames/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/apinames.dir/build.make _deps/rtmidi-build/CMakeFiles/apinames.dir/build
.PHONY : apinames/fast

#=============================================================================
# Target rules for targets named testcapi

# Build rule for target.
testcapi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testcapi
.PHONY : testcapi

# fast build rule for target.
testcapi/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/testcapi.dir/build.make _deps/rtmidi-build/CMakeFiles/testcapi.dir/build
.PHONY : testcapi/fast

#=============================================================================
# Target rules for targets named rt_uninstall

# Build rule for target.
rt_uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rt_uninstall
.PHONY : rt_uninstall

# fast build rule for target.
rt_uninstall/fast:
	$(MAKE) $(MAKESILENT) -f _deps/rtmidi-build/CMakeFiles/rt_uninstall.dir/build.make _deps/rtmidi-build/CMakeFiles/rt_uninstall.dir/build
.PHONY : rt_uninstall/fast

_deps/imgui-src/backends/imgui_impl_sdl2.o: _deps/imgui-src/backends/imgui_impl_sdl2.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl2.o

# target to build an object file
_deps/imgui-src/backends/imgui_impl_sdl2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/backends/imgui_impl_sdl2.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl2.cpp.o

_deps/imgui-src/backends/imgui_impl_sdl2.i: _deps/imgui-src/backends/imgui_impl_sdl2.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl2.i

# target to preprocess a source file
_deps/imgui-src/backends/imgui_impl_sdl2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/backends/imgui_impl_sdl2.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl2.cpp.i

_deps/imgui-src/backends/imgui_impl_sdl2.s: _deps/imgui-src/backends/imgui_impl_sdl2.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl2.s

# target to generate assembly for a file
_deps/imgui-src/backends/imgui_impl_sdl2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/backends/imgui_impl_sdl2.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl2.cpp.s

_deps/imgui-src/backends/imgui_impl_sdlrenderer2.o: _deps/imgui-src/backends/imgui_impl_sdlrenderer2.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_sdlrenderer2.o

# target to build an object file
_deps/imgui-src/backends/imgui_impl_sdlrenderer2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/backends/imgui_impl_sdlrenderer2.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_sdlrenderer2.cpp.o

_deps/imgui-src/backends/imgui_impl_sdlrenderer2.i: _deps/imgui-src/backends/imgui_impl_sdlrenderer2.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_sdlrenderer2.i

# target to preprocess a source file
_deps/imgui-src/backends/imgui_impl_sdlrenderer2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/backends/imgui_impl_sdlrenderer2.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_sdlrenderer2.cpp.i

_deps/imgui-src/backends/imgui_impl_sdlrenderer2.s: _deps/imgui-src/backends/imgui_impl_sdlrenderer2.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_sdlrenderer2.s

# target to generate assembly for a file
_deps/imgui-src/backends/imgui_impl_sdlrenderer2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/backends/imgui_impl_sdlrenderer2.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_sdlrenderer2.cpp.s

_deps/imgui-src/imgui.o: _deps/imgui-src/imgui.cpp.o
.PHONY : _deps/imgui-src/imgui.o

# target to build an object file
_deps/imgui-src/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui.cpp.o
.PHONY : _deps/imgui-src/imgui.cpp.o

_deps/imgui-src/imgui.i: _deps/imgui-src/imgui.cpp.i
.PHONY : _deps/imgui-src/imgui.i

# target to preprocess a source file
_deps/imgui-src/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui.cpp.i
.PHONY : _deps/imgui-src/imgui.cpp.i

_deps/imgui-src/imgui.s: _deps/imgui-src/imgui.cpp.s
.PHONY : _deps/imgui-src/imgui.s

# target to generate assembly for a file
_deps/imgui-src/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui.cpp.s
.PHONY : _deps/imgui-src/imgui.cpp.s

_deps/imgui-src/imgui_demo.o: _deps/imgui-src/imgui_demo.cpp.o
.PHONY : _deps/imgui-src/imgui_demo.o

# target to build an object file
_deps/imgui-src/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui_demo.cpp.o
.PHONY : _deps/imgui-src/imgui_demo.cpp.o

_deps/imgui-src/imgui_demo.i: _deps/imgui-src/imgui_demo.cpp.i
.PHONY : _deps/imgui-src/imgui_demo.i

# target to preprocess a source file
_deps/imgui-src/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui_demo.cpp.i
.PHONY : _deps/imgui-src/imgui_demo.cpp.i

_deps/imgui-src/imgui_demo.s: _deps/imgui-src/imgui_demo.cpp.s
.PHONY : _deps/imgui-src/imgui_demo.s

# target to generate assembly for a file
_deps/imgui-src/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui_demo.cpp.s
.PHONY : _deps/imgui-src/imgui_demo.cpp.s

_deps/imgui-src/imgui_draw.o: _deps/imgui-src/imgui_draw.cpp.o
.PHONY : _deps/imgui-src/imgui_draw.o

# target to build an object file
_deps/imgui-src/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui_draw.cpp.o
.PHONY : _deps/imgui-src/imgui_draw.cpp.o

_deps/imgui-src/imgui_draw.i: _deps/imgui-src/imgui_draw.cpp.i
.PHONY : _deps/imgui-src/imgui_draw.i

# target to preprocess a source file
_deps/imgui-src/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui_draw.cpp.i
.PHONY : _deps/imgui-src/imgui_draw.cpp.i

_deps/imgui-src/imgui_draw.s: _deps/imgui-src/imgui_draw.cpp.s
.PHONY : _deps/imgui-src/imgui_draw.s

# target to generate assembly for a file
_deps/imgui-src/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui_draw.cpp.s
.PHONY : _deps/imgui-src/imgui_draw.cpp.s

_deps/imgui-src/imgui_tables.o: _deps/imgui-src/imgui_tables.cpp.o
.PHONY : _deps/imgui-src/imgui_tables.o

# target to build an object file
_deps/imgui-src/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui_tables.cpp.o
.PHONY : _deps/imgui-src/imgui_tables.cpp.o

_deps/imgui-src/imgui_tables.i: _deps/imgui-src/imgui_tables.cpp.i
.PHONY : _deps/imgui-src/imgui_tables.i

# target to preprocess a source file
_deps/imgui-src/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui_tables.cpp.i
.PHONY : _deps/imgui-src/imgui_tables.cpp.i

_deps/imgui-src/imgui_tables.s: _deps/imgui-src/imgui_tables.cpp.s
.PHONY : _deps/imgui-src/imgui_tables.s

# target to generate assembly for a file
_deps/imgui-src/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui_tables.cpp.s
.PHONY : _deps/imgui-src/imgui_tables.cpp.s

_deps/imgui-src/imgui_widgets.o: _deps/imgui-src/imgui_widgets.cpp.o
.PHONY : _deps/imgui-src/imgui_widgets.o

# target to build an object file
_deps/imgui-src/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui_widgets.cpp.o
.PHONY : _deps/imgui-src/imgui_widgets.cpp.o

_deps/imgui-src/imgui_widgets.i: _deps/imgui-src/imgui_widgets.cpp.i
.PHONY : _deps/imgui-src/imgui_widgets.i

# target to preprocess a source file
_deps/imgui-src/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui_widgets.cpp.i
.PHONY : _deps/imgui-src/imgui_widgets.cpp.i

_deps/imgui-src/imgui_widgets.s: _deps/imgui-src/imgui_widgets.cpp.s
.PHONY : _deps/imgui-src/imgui_widgets.s

# target to generate assembly for a file
_deps/imgui-src/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui_widgets.cpp.s
.PHONY : _deps/imgui-src/imgui_widgets.cpp.s

_deps/rtmidi-src/RtMidi.o: _deps/rtmidi-src/RtMidi.cpp.o
.PHONY : _deps/rtmidi-src/RtMidi.o

# target to build an object file
_deps/rtmidi-src/RtMidi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtmidi_lib.dir/build.make CMakeFiles/rtmidi_lib.dir/_deps/rtmidi-src/RtMidi.cpp.o
.PHONY : _deps/rtmidi-src/RtMidi.cpp.o

_deps/rtmidi-src/RtMidi.i: _deps/rtmidi-src/RtMidi.cpp.i
.PHONY : _deps/rtmidi-src/RtMidi.i

# target to preprocess a source file
_deps/rtmidi-src/RtMidi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtmidi_lib.dir/build.make CMakeFiles/rtmidi_lib.dir/_deps/rtmidi-src/RtMidi.cpp.i
.PHONY : _deps/rtmidi-src/RtMidi.cpp.i

_deps/rtmidi-src/RtMidi.s: _deps/rtmidi-src/RtMidi.cpp.s
.PHONY : _deps/rtmidi-src/RtMidi.s

# target to generate assembly for a file
_deps/rtmidi-src/RtMidi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtmidi_lib.dir/build.make CMakeFiles/rtmidi_lib.dir/_deps/rtmidi-src/RtMidi.cpp.s
.PHONY : _deps/rtmidi-src/RtMidi.cpp.s

src/build_bin.o: src/build_bin.cpp.o
.PHONY : src/build_bin.o

# target to build an object file
src/build_bin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_build_bin.dir/build.make CMakeFiles/drumrom_build_bin.dir/src/build_bin.cpp.o
.PHONY : src/build_bin.cpp.o

src/build_bin.i: src/build_bin.cpp.i
.PHONY : src/build_bin.i

# target to preprocess a source file
src/build_bin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_build_bin.dir/build.make CMakeFiles/drumrom_build_bin.dir/src/build_bin.cpp.i
.PHONY : src/build_bin.cpp.i

src/build_bin.s: src/build_bin.cpp.s
.PHONY : src/build_bin.s

# target to generate assembly for a file
src/build_bin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_build_bin.dir/build.make CMakeFiles/drumrom_build_bin.dir/src/build_bin.cpp.s
.PHONY : src/build_bin.cpp.s

src/main_imgui.o: src/main_imgui.cpp.o
.PHONY : src/main_imgui.o

# target to build an object file
src/main_imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_imgui.cpp.o
.PHONY : src/main_imgui.cpp.o

src/main_imgui.i: src/main_imgui.cpp.i
.PHONY : src/main_imgui.i

# target to preprocess a source file
src/main_imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_imgui.cpp.i
.PHONY : src/main_imgui.cpp.i

src/main_imgui.s: src/main_imgui.cpp.s
.PHONY : src/main_imgui.s

# target to generate assembly for a file
src/main_imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_imgui.cpp.s
.PHONY : src/main_imgui.cpp.s

src/main_ui_editor_dispatch.o: src/main_ui_editor_dispatch.cpp.o
.PHONY : src/main_ui_editor_dispatch.o

# target to build an object file
src/main_ui_editor_dispatch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_editor_dispatch.cpp.o
.PHONY : src/main_ui_editor_dispatch.cpp.o

src/main_ui_editor_dispatch.i: src/main_ui_editor_dispatch.cpp.i
.PHONY : src/main_ui_editor_dispatch.i

# target to preprocess a source file
src/main_ui_editor_dispatch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_editor_dispatch.cpp.i
.PHONY : src/main_ui_editor_dispatch.cpp.i

src/main_ui_editor_dispatch.s: src/main_ui_editor_dispatch.cpp.s
.PHONY : src/main_ui_editor_dispatch.s

# target to generate assembly for a file
src/main_ui_editor_dispatch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_editor_dispatch.cpp.s
.PHONY : src/main_ui_editor_dispatch.cpp.s

src/main_ui_icons.o: src/main_ui_icons.cpp.o
.PHONY : src/main_ui_icons.o

# target to build an object file
src/main_ui_icons.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_icons.cpp.o
.PHONY : src/main_ui_icons.cpp.o

src/main_ui_icons.i: src/main_ui_icons.cpp.i
.PHONY : src/main_ui_icons.i

# target to preprocess a source file
src/main_ui_icons.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_icons.cpp.i
.PHONY : src/main_ui_icons.cpp.i

src/main_ui_icons.s: src/main_ui_icons.cpp.s
.PHONY : src/main_ui_icons.s

# target to generate assembly for a file
src/main_ui_icons.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_icons.cpp.s
.PHONY : src/main_ui_icons.cpp.s

src/main_ui_midi.o: src/main_ui_midi.cpp.o
.PHONY : src/main_ui_midi.o

# target to build an object file
src/main_ui_midi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_midi.cpp.o
.PHONY : src/main_ui_midi.cpp.o

src/main_ui_midi.i: src/main_ui_midi.cpp.i
.PHONY : src/main_ui_midi.i

# target to preprocess a source file
src/main_ui_midi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_midi.cpp.i
.PHONY : src/main_ui_midi.cpp.i

src/main_ui_midi.s: src/main_ui_midi.cpp.s
.PHONY : src/main_ui_midi.s

# target to generate assembly for a file
src/main_ui_midi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_midi.cpp.s
.PHONY : src/main_ui_midi.cpp.s

src/main_ui_orchestration.o: src/main_ui_orchestration.cpp.o
.PHONY : src/main_ui_orchestration.o

# target to build an object file
src/main_ui_orchestration.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_orchestration.cpp.o
.PHONY : src/main_ui_orchestration.cpp.o

src/main_ui_orchestration.i: src/main_ui_orchestration.cpp.i
.PHONY : src/main_ui_orchestration.i

# target to preprocess a source file
src/main_ui_orchestration.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_orchestration.cpp.i
.PHONY : src/main_ui_orchestration.cpp.i

src/main_ui_orchestration.s: src/main_ui_orchestration.cpp.s
.PHONY : src/main_ui_orchestration.s

# target to generate assembly for a file
src/main_ui_orchestration.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_orchestration.cpp.s
.PHONY : src/main_ui_orchestration.cpp.s

src/main_ui_overlay_controls.o: src/main_ui_overlay_controls.cpp.o
.PHONY : src/main_ui_overlay_controls.o

# target to build an object file
src/main_ui_overlay_controls.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_overlay_controls.cpp.o
.PHONY : src/main_ui_overlay_controls.cpp.o

src/main_ui_overlay_controls.i: src/main_ui_overlay_controls.cpp.i
.PHONY : src/main_ui_overlay_controls.i

# target to preprocess a source file
src/main_ui_overlay_controls.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_overlay_controls.cpp.i
.PHONY : src/main_ui_overlay_controls.cpp.i

src/main_ui_overlay_controls.s: src/main_ui_overlay_controls.cpp.s
.PHONY : src/main_ui_overlay_controls.s

# target to generate assembly for a file
src/main_ui_overlay_controls.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_overlay_controls.cpp.s
.PHONY : src/main_ui_overlay_controls.cpp.s

src/main_ui_overlay_waveform.o: src/main_ui_overlay_waveform.cpp.o
.PHONY : src/main_ui_overlay_waveform.o

# target to build an object file
src/main_ui_overlay_waveform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_overlay_waveform.cpp.o
.PHONY : src/main_ui_overlay_waveform.cpp.o

src/main_ui_overlay_waveform.i: src/main_ui_overlay_waveform.cpp.i
.PHONY : src/main_ui_overlay_waveform.i

# target to preprocess a source file
src/main_ui_overlay_waveform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_overlay_waveform.cpp.i
.PHONY : src/main_ui_overlay_waveform.cpp.i

src/main_ui_overlay_waveform.s: src/main_ui_overlay_waveform.cpp.s
.PHONY : src/main_ui_overlay_waveform.s

# target to generate assembly for a file
src/main_ui_overlay_waveform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_overlay_waveform.cpp.s
.PHONY : src/main_ui_overlay_waveform.cpp.s

src/main_ui_runtime_bootstrap.o: src/main_ui_runtime_bootstrap.cpp.o
.PHONY : src/main_ui_runtime_bootstrap.o

# target to build an object file
src/main_ui_runtime_bootstrap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_runtime_bootstrap.cpp.o
.PHONY : src/main_ui_runtime_bootstrap.cpp.o

src/main_ui_runtime_bootstrap.i: src/main_ui_runtime_bootstrap.cpp.i
.PHONY : src/main_ui_runtime_bootstrap.i

# target to preprocess a source file
src/main_ui_runtime_bootstrap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_runtime_bootstrap.cpp.i
.PHONY : src/main_ui_runtime_bootstrap.cpp.i

src/main_ui_runtime_bootstrap.s: src/main_ui_runtime_bootstrap.cpp.s
.PHONY : src/main_ui_runtime_bootstrap.s

# target to generate assembly for a file
src/main_ui_runtime_bootstrap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_runtime_bootstrap.cpp.s
.PHONY : src/main_ui_runtime_bootstrap.cpp.s

src/main_ui_runtime_cleanup.o: src/main_ui_runtime_cleanup.cpp.o
.PHONY : src/main_ui_runtime_cleanup.o

# target to build an object file
src/main_ui_runtime_cleanup.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_runtime_cleanup.cpp.o
.PHONY : src/main_ui_runtime_cleanup.cpp.o

src/main_ui_runtime_cleanup.i: src/main_ui_runtime_cleanup.cpp.i
.PHONY : src/main_ui_runtime_cleanup.i

# target to preprocess a source file
src/main_ui_runtime_cleanup.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_runtime_cleanup.cpp.i
.PHONY : src/main_ui_runtime_cleanup.cpp.i

src/main_ui_runtime_cleanup.s: src/main_ui_runtime_cleanup.cpp.s
.PHONY : src/main_ui_runtime_cleanup.s

# target to generate assembly for a file
src/main_ui_runtime_cleanup.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_runtime_cleanup.cpp.s
.PHONY : src/main_ui_runtime_cleanup.cpp.s

src/main_ui_runtime_events.o: src/main_ui_runtime_events.cpp.o
.PHONY : src/main_ui_runtime_events.o

# target to build an object file
src/main_ui_runtime_events.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_runtime_events.cpp.o
.PHONY : src/main_ui_runtime_events.cpp.o

src/main_ui_runtime_events.i: src/main_ui_runtime_events.cpp.i
.PHONY : src/main_ui_runtime_events.i

# target to preprocess a source file
src/main_ui_runtime_events.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_runtime_events.cpp.i
.PHONY : src/main_ui_runtime_events.cpp.i

src/main_ui_runtime_events.s: src/main_ui_runtime_events.cpp.s
.PHONY : src/main_ui_runtime_events.s

# target to generate assembly for a file
src/main_ui_runtime_events.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_runtime_events.cpp.s
.PHONY : src/main_ui_runtime_events.cpp.s

src/main_ui_runtime_frame.o: src/main_ui_runtime_frame.cpp.o
.PHONY : src/main_ui_runtime_frame.o

# target to build an object file
src/main_ui_runtime_frame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_runtime_frame.cpp.o
.PHONY : src/main_ui_runtime_frame.cpp.o

src/main_ui_runtime_frame.i: src/main_ui_runtime_frame.cpp.i
.PHONY : src/main_ui_runtime_frame.i

# target to preprocess a source file
src/main_ui_runtime_frame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_runtime_frame.cpp.i
.PHONY : src/main_ui_runtime_frame.cpp.i

src/main_ui_runtime_frame.s: src/main_ui_runtime_frame.cpp.s
.PHONY : src/main_ui_runtime_frame.s

# target to generate assembly for a file
src/main_ui_runtime_frame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_runtime_frame.cpp.s
.PHONY : src/main_ui_runtime_frame.cpp.s

src/main_ui_runtime_input.o: src/main_ui_runtime_input.cpp.o
.PHONY : src/main_ui_runtime_input.o

# target to build an object file
src/main_ui_runtime_input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_runtime_input.cpp.o
.PHONY : src/main_ui_runtime_input.cpp.o

src/main_ui_runtime_input.i: src/main_ui_runtime_input.cpp.i
.PHONY : src/main_ui_runtime_input.i

# target to preprocess a source file
src/main_ui_runtime_input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_runtime_input.cpp.i
.PHONY : src/main_ui_runtime_input.cpp.i

src/main_ui_runtime_input.s: src/main_ui_runtime_input.cpp.s
.PHONY : src/main_ui_runtime_input.s

# target to generate assembly for a file
src/main_ui_runtime_input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_runtime_input.cpp.s
.PHONY : src/main_ui_runtime_input.cpp.s

src/main_ui_runtime_startup.o: src/main_ui_runtime_startup.cpp.o
.PHONY : src/main_ui_runtime_startup.o

# target to build an object file
src/main_ui_runtime_startup.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_runtime_startup.cpp.o
.PHONY : src/main_ui_runtime_startup.cpp.o

src/main_ui_runtime_startup.i: src/main_ui_runtime_startup.cpp.i
.PHONY : src/main_ui_runtime_startup.i

# target to preprocess a source file
src/main_ui_runtime_startup.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_runtime_startup.cpp.i
.PHONY : src/main_ui_runtime_startup.cpp.i

src/main_ui_runtime_startup.s: src/main_ui_runtime_startup.cpp.s
.PHONY : src/main_ui_runtime_startup.s

# target to generate assembly for a file
src/main_ui_runtime_startup.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/main_ui_runtime_startup.cpp.s
.PHONY : src/main_ui_runtime_startup.cpp.s

src/onerom_usb_routing.o: src/onerom_usb_routing.cpp.o
.PHONY : src/onerom_usb_routing.o

# target to build an object file
src/onerom_usb_routing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/onerom_usb_routing.cpp.o
.PHONY : src/onerom_usb_routing.cpp.o

src/onerom_usb_routing.i: src/onerom_usb_routing.cpp.i
.PHONY : src/onerom_usb_routing.i

# target to preprocess a source file
src/onerom_usb_routing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/onerom_usb_routing.cpp.i
.PHONY : src/onerom_usb_routing.cpp.i

src/onerom_usb_routing.s: src/onerom_usb_routing.cpp.s
.PHONY : src/onerom_usb_routing.s

# target to generate assembly for a file
src/onerom_usb_routing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/onerom_usb_routing.cpp.s
.PHONY : src/onerom_usb_routing.cpp.s

src/preset_browser_fs.o: src/preset_browser_fs.cpp.o
.PHONY : src/preset_browser_fs.o

# target to build an object file
src/preset_browser_fs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/preset_browser_fs.cpp.o
.PHONY : src/preset_browser_fs.cpp.o

src/preset_browser_fs.i: src/preset_browser_fs.cpp.i
.PHONY : src/preset_browser_fs.i

# target to preprocess a source file
src/preset_browser_fs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/preset_browser_fs.cpp.i
.PHONY : src/preset_browser_fs.cpp.i

src/preset_browser_fs.s: src/preset_browser_fs.cpp.s
.PHONY : src/preset_browser_fs.s

# target to generate assembly for a file
src/preset_browser_fs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/preset_browser_fs.cpp.s
.PHONY : src/preset_browser_fs.cpp.s

src/sample_browser_fs.o: src/sample_browser_fs.cpp.o
.PHONY : src/sample_browser_fs.o

# target to build an object file
src/sample_browser_fs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/sample_browser_fs.cpp.o
.PHONY : src/sample_browser_fs.cpp.o

src/sample_browser_fs.i: src/sample_browser_fs.cpp.i
.PHONY : src/sample_browser_fs.i

# target to preprocess a source file
src/sample_browser_fs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/sample_browser_fs.cpp.i
.PHONY : src/sample_browser_fs.cpp.i

src/sample_browser_fs.s: src/sample_browser_fs.cpp.s
.PHONY : src/sample_browser_fs.s

# target to generate assembly for a file
src/sample_browser_fs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/sample_browser_fs.cpp.s
.PHONY : src/sample_browser_fs.cpp.s

src/settings_io.o: src/settings_io.cpp.o
.PHONY : src/settings_io.o

# target to build an object file
src/settings_io.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/settings_io.cpp.o
.PHONY : src/settings_io.cpp.o

src/settings_io.i: src/settings_io.cpp.i
.PHONY : src/settings_io.i

# target to preprocess a source file
src/settings_io.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/settings_io.cpp.i
.PHONY : src/settings_io.cpp.i

src/settings_io.s: src/settings_io.cpp.s
.PHONY : src/settings_io.s

# target to generate assembly for a file
src/settings_io.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/settings_io.cpp.s
.PHONY : src/settings_io.cpp.s

src/synth.o: src/synth.cpp.o
.PHONY : src/synth.o

# target to build an object file
src/synth.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/src/synth.cpp.o
.PHONY : src/synth.cpp.o

src/synth.i: src/synth.cpp.i
.PHONY : src/synth.i

# target to preprocess a source file
src/synth.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/src/synth.cpp.i
.PHONY : src/synth.cpp.i

src/synth.s: src/synth.cpp.s
.PHONY : src/synth.s

# target to generate assembly for a file
src/synth.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/src/synth.cpp.s
.PHONY : src/synth.cpp.s

src/synth_elements.o: src/synth_elements.cpp.o
.PHONY : src/synth_elements.o

# target to build an object file
src/synth_elements.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/src/synth_elements.cpp.o
.PHONY : src/synth_elements.cpp.o

src/synth_elements.i: src/synth_elements.cpp.i
.PHONY : src/synth_elements.i

# target to preprocess a source file
src/synth_elements.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/src/synth_elements.cpp.i
.PHONY : src/synth_elements.cpp.i

src/synth_elements.s: src/synth_elements.cpp.s
.PHONY : src/synth_elements.s

# target to generate assembly for a file
src/synth_elements.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/src/synth_elements.cpp.s
.PHONY : src/synth_elements.cpp.s

src/synth_elements_exact.o: src/synth_elements_exact.cpp.o
.PHONY : src/synth_elements_exact.o

# target to build an object file
src/synth_elements_exact.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/src/synth_elements_exact.cpp.o
.PHONY : src/synth_elements_exact.cpp.o

src/synth_elements_exact.i: src/synth_elements_exact.cpp.i
.PHONY : src/synth_elements_exact.i

# target to preprocess a source file
src/synth_elements_exact.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/src/synth_elements_exact.cpp.i
.PHONY : src/synth_elements_exact.cpp.i

src/synth_elements_exact.s: src/synth_elements_exact.cpp.s
.PHONY : src/synth_elements_exact.s

# target to generate assembly for a file
src/synth_elements_exact.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/src/synth_elements_exact.cpp.s
.PHONY : src/synth_elements_exact.cpp.s

src/synth_freeverb.o: src/synth_freeverb.cpp.o
.PHONY : src/synth_freeverb.o

# target to build an object file
src/synth_freeverb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/src/synth_freeverb.cpp.o
.PHONY : src/synth_freeverb.cpp.o

src/synth_freeverb.i: src/synth_freeverb.cpp.i
.PHONY : src/synth_freeverb.i

# target to preprocess a source file
src/synth_freeverb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/src/synth_freeverb.cpp.i
.PHONY : src/synth_freeverb.cpp.i

src/synth_freeverb.s: src/synth_freeverb.cpp.s
.PHONY : src/synth_freeverb.s

# target to generate assembly for a file
src/synth_freeverb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/src/synth_freeverb.cpp.s
.PHONY : src/synth_freeverb.cpp.s

src/ui_bottom_toolbar.o: src/ui_bottom_toolbar.cpp.o
.PHONY : src/ui_bottom_toolbar.o

# target to build an object file
src/ui_bottom_toolbar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/ui_bottom_toolbar.cpp.o
.PHONY : src/ui_bottom_toolbar.cpp.o

src/ui_bottom_toolbar.i: src/ui_bottom_toolbar.cpp.i
.PHONY : src/ui_bottom_toolbar.i

# target to preprocess a source file
src/ui_bottom_toolbar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/ui_bottom_toolbar.cpp.i
.PHONY : src/ui_bottom_toolbar.cpp.i

src/ui_bottom_toolbar.s: src/ui_bottom_toolbar.cpp.s
.PHONY : src/ui_bottom_toolbar.s

# target to generate assembly for a file
src/ui_bottom_toolbar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/ui_bottom_toolbar.cpp.s
.PHONY : src/ui_bottom_toolbar.cpp.s

src/ui_editor_page.o: src/ui_editor_page.cpp.o
.PHONY : src/ui_editor_page.o

# target to build an object file
src/ui_editor_page.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/ui_editor_page.cpp.o
.PHONY : src/ui_editor_page.cpp.o

src/ui_editor_page.i: src/ui_editor_page.cpp.i
.PHONY : src/ui_editor_page.i

# target to preprocess a source file
src/ui_editor_page.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/ui_editor_page.cpp.i
.PHONY : src/ui_editor_page.cpp.i

src/ui_editor_page.s: src/ui_editor_page.cpp.s
.PHONY : src/ui_editor_page.s

# target to generate assembly for a file
src/ui_editor_page.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/ui_editor_page.cpp.s
.PHONY : src/ui_editor_page.cpp.s

src/ui_pin_matrix_page.o: src/ui_pin_matrix_page.cpp.o
.PHONY : src/ui_pin_matrix_page.o

# target to build an object file
src/ui_pin_matrix_page.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/ui_pin_matrix_page.cpp.o
.PHONY : src/ui_pin_matrix_page.cpp.o

src/ui_pin_matrix_page.i: src/ui_pin_matrix_page.cpp.i
.PHONY : src/ui_pin_matrix_page.i

# target to preprocess a source file
src/ui_pin_matrix_page.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/ui_pin_matrix_page.cpp.i
.PHONY : src/ui_pin_matrix_page.cpp.i

src/ui_pin_matrix_page.s: src/ui_pin_matrix_page.cpp.s
.PHONY : src/ui_pin_matrix_page.s

# target to generate assembly for a file
src/ui_pin_matrix_page.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/ui_pin_matrix_page.cpp.s
.PHONY : src/ui_pin_matrix_page.cpp.s

src/ui_settings_page.o: src/ui_settings_page.cpp.o
.PHONY : src/ui_settings_page.o

# target to build an object file
src/ui_settings_page.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/ui_settings_page.cpp.o
.PHONY : src/ui_settings_page.cpp.o

src/ui_settings_page.i: src/ui_settings_page.cpp.i
.PHONY : src/ui_settings_page.i

# target to preprocess a source file
src/ui_settings_page.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/ui_settings_page.cpp.i
.PHONY : src/ui_settings_page.cpp.i

src/ui_settings_page.s: src/ui_settings_page.cpp.s
.PHONY : src/ui_settings_page.s

# target to generate assembly for a file
src/ui_settings_page.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_gui.dir/build.make CMakeFiles/drumrom_gui.dir/src/ui_settings_page.cpp.s
.PHONY : src/ui_settings_page.cpp.s

third_party/mutable/elements/dsp/exciter.o: third_party/mutable/elements/dsp/exciter.cc.o
.PHONY : third_party/mutable/elements/dsp/exciter.o

# target to build an object file
third_party/mutable/elements/dsp/exciter.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/dsp/exciter.cc.o
.PHONY : third_party/mutable/elements/dsp/exciter.cc.o

third_party/mutable/elements/dsp/exciter.i: third_party/mutable/elements/dsp/exciter.cc.i
.PHONY : third_party/mutable/elements/dsp/exciter.i

# target to preprocess a source file
third_party/mutable/elements/dsp/exciter.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/dsp/exciter.cc.i
.PHONY : third_party/mutable/elements/dsp/exciter.cc.i

third_party/mutable/elements/dsp/exciter.s: third_party/mutable/elements/dsp/exciter.cc.s
.PHONY : third_party/mutable/elements/dsp/exciter.s

# target to generate assembly for a file
third_party/mutable/elements/dsp/exciter.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/dsp/exciter.cc.s
.PHONY : third_party/mutable/elements/dsp/exciter.cc.s

third_party/mutable/elements/dsp/multistage_envelope.o: third_party/mutable/elements/dsp/multistage_envelope.cc.o
.PHONY : third_party/mutable/elements/dsp/multistage_envelope.o

# target to build an object file
third_party/mutable/elements/dsp/multistage_envelope.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/dsp/multistage_envelope.cc.o
.PHONY : third_party/mutable/elements/dsp/multistage_envelope.cc.o

third_party/mutable/elements/dsp/multistage_envelope.i: third_party/mutable/elements/dsp/multistage_envelope.cc.i
.PHONY : third_party/mutable/elements/dsp/multistage_envelope.i

# target to preprocess a source file
third_party/mutable/elements/dsp/multistage_envelope.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/dsp/multistage_envelope.cc.i
.PHONY : third_party/mutable/elements/dsp/multistage_envelope.cc.i

third_party/mutable/elements/dsp/multistage_envelope.s: third_party/mutable/elements/dsp/multistage_envelope.cc.s
.PHONY : third_party/mutable/elements/dsp/multistage_envelope.s

# target to generate assembly for a file
third_party/mutable/elements/dsp/multistage_envelope.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/dsp/multistage_envelope.cc.s
.PHONY : third_party/mutable/elements/dsp/multistage_envelope.cc.s

third_party/mutable/elements/dsp/ominous_voice.o: third_party/mutable/elements/dsp/ominous_voice.cc.o
.PHONY : third_party/mutable/elements/dsp/ominous_voice.o

# target to build an object file
third_party/mutable/elements/dsp/ominous_voice.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/dsp/ominous_voice.cc.o
.PHONY : third_party/mutable/elements/dsp/ominous_voice.cc.o

third_party/mutable/elements/dsp/ominous_voice.i: third_party/mutable/elements/dsp/ominous_voice.cc.i
.PHONY : third_party/mutable/elements/dsp/ominous_voice.i

# target to preprocess a source file
third_party/mutable/elements/dsp/ominous_voice.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/dsp/ominous_voice.cc.i
.PHONY : third_party/mutable/elements/dsp/ominous_voice.cc.i

third_party/mutable/elements/dsp/ominous_voice.s: third_party/mutable/elements/dsp/ominous_voice.cc.s
.PHONY : third_party/mutable/elements/dsp/ominous_voice.s

# target to generate assembly for a file
third_party/mutable/elements/dsp/ominous_voice.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/dsp/ominous_voice.cc.s
.PHONY : third_party/mutable/elements/dsp/ominous_voice.cc.s

third_party/mutable/elements/dsp/part.o: third_party/mutable/elements/dsp/part.cc.o
.PHONY : third_party/mutable/elements/dsp/part.o

# target to build an object file
third_party/mutable/elements/dsp/part.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/dsp/part.cc.o
.PHONY : third_party/mutable/elements/dsp/part.cc.o

third_party/mutable/elements/dsp/part.i: third_party/mutable/elements/dsp/part.cc.i
.PHONY : third_party/mutable/elements/dsp/part.i

# target to preprocess a source file
third_party/mutable/elements/dsp/part.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/dsp/part.cc.i
.PHONY : third_party/mutable/elements/dsp/part.cc.i

third_party/mutable/elements/dsp/part.s: third_party/mutable/elements/dsp/part.cc.s
.PHONY : third_party/mutable/elements/dsp/part.s

# target to generate assembly for a file
third_party/mutable/elements/dsp/part.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/dsp/part.cc.s
.PHONY : third_party/mutable/elements/dsp/part.cc.s

third_party/mutable/elements/dsp/resonator.o: third_party/mutable/elements/dsp/resonator.cc.o
.PHONY : third_party/mutable/elements/dsp/resonator.o

# target to build an object file
third_party/mutable/elements/dsp/resonator.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/dsp/resonator.cc.o
.PHONY : third_party/mutable/elements/dsp/resonator.cc.o

third_party/mutable/elements/dsp/resonator.i: third_party/mutable/elements/dsp/resonator.cc.i
.PHONY : third_party/mutable/elements/dsp/resonator.i

# target to preprocess a source file
third_party/mutable/elements/dsp/resonator.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/dsp/resonator.cc.i
.PHONY : third_party/mutable/elements/dsp/resonator.cc.i

third_party/mutable/elements/dsp/resonator.s: third_party/mutable/elements/dsp/resonator.cc.s
.PHONY : third_party/mutable/elements/dsp/resonator.s

# target to generate assembly for a file
third_party/mutable/elements/dsp/resonator.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/dsp/resonator.cc.s
.PHONY : third_party/mutable/elements/dsp/resonator.cc.s

third_party/mutable/elements/dsp/string.o: third_party/mutable/elements/dsp/string.cc.o
.PHONY : third_party/mutable/elements/dsp/string.o

# target to build an object file
third_party/mutable/elements/dsp/string.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/dsp/string.cc.o
.PHONY : third_party/mutable/elements/dsp/string.cc.o

third_party/mutable/elements/dsp/string.i: third_party/mutable/elements/dsp/string.cc.i
.PHONY : third_party/mutable/elements/dsp/string.i

# target to preprocess a source file
third_party/mutable/elements/dsp/string.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/dsp/string.cc.i
.PHONY : third_party/mutable/elements/dsp/string.cc.i

third_party/mutable/elements/dsp/string.s: third_party/mutable/elements/dsp/string.cc.s
.PHONY : third_party/mutable/elements/dsp/string.s

# target to generate assembly for a file
third_party/mutable/elements/dsp/string.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/dsp/string.cc.s
.PHONY : third_party/mutable/elements/dsp/string.cc.s

third_party/mutable/elements/dsp/tube.o: third_party/mutable/elements/dsp/tube.cc.o
.PHONY : third_party/mutable/elements/dsp/tube.o

# target to build an object file
third_party/mutable/elements/dsp/tube.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/dsp/tube.cc.o
.PHONY : third_party/mutable/elements/dsp/tube.cc.o

third_party/mutable/elements/dsp/tube.i: third_party/mutable/elements/dsp/tube.cc.i
.PHONY : third_party/mutable/elements/dsp/tube.i

# target to preprocess a source file
third_party/mutable/elements/dsp/tube.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/dsp/tube.cc.i
.PHONY : third_party/mutable/elements/dsp/tube.cc.i

third_party/mutable/elements/dsp/tube.s: third_party/mutable/elements/dsp/tube.cc.s
.PHONY : third_party/mutable/elements/dsp/tube.s

# target to generate assembly for a file
third_party/mutable/elements/dsp/tube.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/dsp/tube.cc.s
.PHONY : third_party/mutable/elements/dsp/tube.cc.s

third_party/mutable/elements/dsp/voice.o: third_party/mutable/elements/dsp/voice.cc.o
.PHONY : third_party/mutable/elements/dsp/voice.o

# target to build an object file
third_party/mutable/elements/dsp/voice.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/dsp/voice.cc.o
.PHONY : third_party/mutable/elements/dsp/voice.cc.o

third_party/mutable/elements/dsp/voice.i: third_party/mutable/elements/dsp/voice.cc.i
.PHONY : third_party/mutable/elements/dsp/voice.i

# target to preprocess a source file
third_party/mutable/elements/dsp/voice.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/dsp/voice.cc.i
.PHONY : third_party/mutable/elements/dsp/voice.cc.i

third_party/mutable/elements/dsp/voice.s: third_party/mutable/elements/dsp/voice.cc.s
.PHONY : third_party/mutable/elements/dsp/voice.s

# target to generate assembly for a file
third_party/mutable/elements/dsp/voice.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/dsp/voice.cc.s
.PHONY : third_party/mutable/elements/dsp/voice.cc.s

third_party/mutable/elements/resources.o: third_party/mutable/elements/resources.cc.o
.PHONY : third_party/mutable/elements/resources.o

# target to build an object file
third_party/mutable/elements/resources.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/resources.cc.o
.PHONY : third_party/mutable/elements/resources.cc.o

third_party/mutable/elements/resources.i: third_party/mutable/elements/resources.cc.i
.PHONY : third_party/mutable/elements/resources.i

# target to preprocess a source file
third_party/mutable/elements/resources.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/resources.cc.i
.PHONY : third_party/mutable/elements/resources.cc.i

third_party/mutable/elements/resources.s: third_party/mutable/elements/resources.cc.s
.PHONY : third_party/mutable/elements/resources.s

# target to generate assembly for a file
third_party/mutable/elements/resources.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/elements/resources.cc.s
.PHONY : third_party/mutable/elements/resources.cc.s

third_party/mutable/stmlib/dsp/units.o: third_party/mutable/stmlib/dsp/units.cc.o
.PHONY : third_party/mutable/stmlib/dsp/units.o

# target to build an object file
third_party/mutable/stmlib/dsp/units.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/stmlib/dsp/units.cc.o
.PHONY : third_party/mutable/stmlib/dsp/units.cc.o

third_party/mutable/stmlib/dsp/units.i: third_party/mutable/stmlib/dsp/units.cc.i
.PHONY : third_party/mutable/stmlib/dsp/units.i

# target to preprocess a source file
third_party/mutable/stmlib/dsp/units.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/stmlib/dsp/units.cc.i
.PHONY : third_party/mutable/stmlib/dsp/units.cc.i

third_party/mutable/stmlib/dsp/units.s: third_party/mutable/stmlib/dsp/units.cc.s
.PHONY : third_party/mutable/stmlib/dsp/units.s

# target to generate assembly for a file
third_party/mutable/stmlib/dsp/units.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/stmlib/dsp/units.cc.s
.PHONY : third_party/mutable/stmlib/dsp/units.cc.s

third_party/mutable/stmlib/utils/random.o: third_party/mutable/stmlib/utils/random.cc.o
.PHONY : third_party/mutable/stmlib/utils/random.o

# target to build an object file
third_party/mutable/stmlib/utils/random.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/stmlib/utils/random.cc.o
.PHONY : third_party/mutable/stmlib/utils/random.cc.o

third_party/mutable/stmlib/utils/random.i: third_party/mutable/stmlib/utils/random.cc.i
.PHONY : third_party/mutable/stmlib/utils/random.i

# target to preprocess a source file
third_party/mutable/stmlib/utils/random.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/stmlib/utils/random.cc.i
.PHONY : third_party/mutable/stmlib/utils/random.cc.i

third_party/mutable/stmlib/utils/random.s: third_party/mutable/stmlib/utils/random.cc.s
.PHONY : third_party/mutable/stmlib/utils/random.s

# target to generate assembly for a file
third_party/mutable/stmlib/utils/random.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drumrom_synth.dir/build.make CMakeFiles/drumrom_synth.dir/third_party/mutable/stmlib/utils/random.cc.s
.PHONY : third_party/mutable/stmlib/utils/random.cc.s

tools/synth_demo.o: tools/synth_demo.cpp.o
.PHONY : tools/synth_demo.o

# target to build an object file
tools/synth_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/synth_demo.dir/build.make CMakeFiles/synth_demo.dir/tools/synth_demo.cpp.o
.PHONY : tools/synth_demo.cpp.o

tools/synth_demo.i: tools/synth_demo.cpp.i
.PHONY : tools/synth_demo.i

# target to preprocess a source file
tools/synth_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/synth_demo.dir/build.make CMakeFiles/synth_demo.dir/tools/synth_demo.cpp.i
.PHONY : tools/synth_demo.cpp.i

tools/synth_demo.s: tools/synth_demo.cpp.s
.PHONY : tools/synth_demo.s

# target to generate assembly for a file
tools/synth_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/synth_demo.dir/build.make CMakeFiles/synth_demo.dir/tools/synth_demo.cpp.s
.PHONY : tools/synth_demo.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... rt_uninstall"
	@echo "... apinames"
	@echo "... cmidiin"
	@echo "... drumrom_build_bin"
	@echo "... drumrom_gui"
	@echo "... drumrom_synth"
	@echo "... imgui_lib"
	@echo "... midiclock"
	@echo "... midiout"
	@echo "... midiprobe"
	@echo "... qmidiin"
	@echo "... rtmidi"
	@echo "... rtmidi_lib"
	@echo "... synth_demo"
	@echo "... sysextest"
	@echo "... testcapi"
	@echo "... _deps/imgui-src/backends/imgui_impl_sdl2.o"
	@echo "... _deps/imgui-src/backends/imgui_impl_sdl2.i"
	@echo "... _deps/imgui-src/backends/imgui_impl_sdl2.s"
	@echo "... _deps/imgui-src/backends/imgui_impl_sdlrenderer2.o"
	@echo "... _deps/imgui-src/backends/imgui_impl_sdlrenderer2.i"
	@echo "... _deps/imgui-src/backends/imgui_impl_sdlrenderer2.s"
	@echo "... _deps/imgui-src/imgui.o"
	@echo "... _deps/imgui-src/imgui.i"
	@echo "... _deps/imgui-src/imgui.s"
	@echo "... _deps/imgui-src/imgui_demo.o"
	@echo "... _deps/imgui-src/imgui_demo.i"
	@echo "... _deps/imgui-src/imgui_demo.s"
	@echo "... _deps/imgui-src/imgui_draw.o"
	@echo "... _deps/imgui-src/imgui_draw.i"
	@echo "... _deps/imgui-src/imgui_draw.s"
	@echo "... _deps/imgui-src/imgui_tables.o"
	@echo "... _deps/imgui-src/imgui_tables.i"
	@echo "... _deps/imgui-src/imgui_tables.s"
	@echo "... _deps/imgui-src/imgui_widgets.o"
	@echo "... _deps/imgui-src/imgui_widgets.i"
	@echo "... _deps/imgui-src/imgui_widgets.s"
	@echo "... _deps/rtmidi-src/RtMidi.o"
	@echo "... _deps/rtmidi-src/RtMidi.i"
	@echo "... _deps/rtmidi-src/RtMidi.s"
	@echo "... src/build_bin.o"
	@echo "... src/build_bin.i"
	@echo "... src/build_bin.s"
	@echo "... src/main_imgui.o"
	@echo "... src/main_imgui.i"
	@echo "... src/main_imgui.s"
	@echo "... src/main_ui_editor_dispatch.o"
	@echo "... src/main_ui_editor_dispatch.i"
	@echo "... src/main_ui_editor_dispatch.s"
	@echo "... src/main_ui_icons.o"
	@echo "... src/main_ui_icons.i"
	@echo "... src/main_ui_icons.s"
	@echo "... src/main_ui_midi.o"
	@echo "... src/main_ui_midi.i"
	@echo "... src/main_ui_midi.s"
	@echo "... src/main_ui_orchestration.o"
	@echo "... src/main_ui_orchestration.i"
	@echo "... src/main_ui_orchestration.s"
	@echo "... src/main_ui_overlay_controls.o"
	@echo "... src/main_ui_overlay_controls.i"
	@echo "... src/main_ui_overlay_controls.s"
	@echo "... src/main_ui_overlay_waveform.o"
	@echo "... src/main_ui_overlay_waveform.i"
	@echo "... src/main_ui_overlay_waveform.s"
	@echo "... src/main_ui_runtime_bootstrap.o"
	@echo "... src/main_ui_runtime_bootstrap.i"
	@echo "... src/main_ui_runtime_bootstrap.s"
	@echo "... src/main_ui_runtime_cleanup.o"
	@echo "... src/main_ui_runtime_cleanup.i"
	@echo "... src/main_ui_runtime_cleanup.s"
	@echo "... src/main_ui_runtime_events.o"
	@echo "... src/main_ui_runtime_events.i"
	@echo "... src/main_ui_runtime_events.s"
	@echo "... src/main_ui_runtime_frame.o"
	@echo "... src/main_ui_runtime_frame.i"
	@echo "... src/main_ui_runtime_frame.s"
	@echo "... src/main_ui_runtime_input.o"
	@echo "... src/main_ui_runtime_input.i"
	@echo "... src/main_ui_runtime_input.s"
	@echo "... src/main_ui_runtime_startup.o"
	@echo "... src/main_ui_runtime_startup.i"
	@echo "... src/main_ui_runtime_startup.s"
	@echo "... src/onerom_usb_routing.o"
	@echo "... src/onerom_usb_routing.i"
	@echo "... src/onerom_usb_routing.s"
	@echo "... src/preset_browser_fs.o"
	@echo "... src/preset_browser_fs.i"
	@echo "... src/preset_browser_fs.s"
	@echo "... src/sample_browser_fs.o"
	@echo "... src/sample_browser_fs.i"
	@echo "... src/sample_browser_fs.s"
	@echo "... src/settings_io.o"
	@echo "... src/settings_io.i"
	@echo "... src/settings_io.s"
	@echo "... src/synth.o"
	@echo "... src/synth.i"
	@echo "... src/synth.s"
	@echo "... src/synth_elements.o"
	@echo "... src/synth_elements.i"
	@echo "... src/synth_elements.s"
	@echo "... src/synth_elements_exact.o"
	@echo "... src/synth_elements_exact.i"
	@echo "... src/synth_elements_exact.s"
	@echo "... src/synth_freeverb.o"
	@echo "... src/synth_freeverb.i"
	@echo "... src/synth_freeverb.s"
	@echo "... src/ui_bottom_toolbar.o"
	@echo "... src/ui_bottom_toolbar.i"
	@echo "... src/ui_bottom_toolbar.s"
	@echo "... src/ui_editor_page.o"
	@echo "... src/ui_editor_page.i"
	@echo "... src/ui_editor_page.s"
	@echo "... src/ui_pin_matrix_page.o"
	@echo "... src/ui_pin_matrix_page.i"
	@echo "... src/ui_pin_matrix_page.s"
	@echo "... src/ui_settings_page.o"
	@echo "... src/ui_settings_page.i"
	@echo "... src/ui_settings_page.s"
	@echo "... third_party/mutable/elements/dsp/exciter.o"
	@echo "... third_party/mutable/elements/dsp/exciter.i"
	@echo "... third_party/mutable/elements/dsp/exciter.s"
	@echo "... third_party/mutable/elements/dsp/multistage_envelope.o"
	@echo "... third_party/mutable/elements/dsp/multistage_envelope.i"
	@echo "... third_party/mutable/elements/dsp/multistage_envelope.s"
	@echo "... third_party/mutable/elements/dsp/ominous_voice.o"
	@echo "... third_party/mutable/elements/dsp/ominous_voice.i"
	@echo "... third_party/mutable/elements/dsp/ominous_voice.s"
	@echo "... third_party/mutable/elements/dsp/part.o"
	@echo "... third_party/mutable/elements/dsp/part.i"
	@echo "... third_party/mutable/elements/dsp/part.s"
	@echo "... third_party/mutable/elements/dsp/resonator.o"
	@echo "... third_party/mutable/elements/dsp/resonator.i"
	@echo "... third_party/mutable/elements/dsp/resonator.s"
	@echo "... third_party/mutable/elements/dsp/string.o"
	@echo "... third_party/mutable/elements/dsp/string.i"
	@echo "... third_party/mutable/elements/dsp/string.s"
	@echo "... third_party/mutable/elements/dsp/tube.o"
	@echo "... third_party/mutable/elements/dsp/tube.i"
	@echo "... third_party/mutable/elements/dsp/tube.s"
	@echo "... third_party/mutable/elements/dsp/voice.o"
	@echo "... third_party/mutable/elements/dsp/voice.i"
	@echo "... third_party/mutable/elements/dsp/voice.s"
	@echo "... third_party/mutable/elements/resources.o"
	@echo "... third_party/mutable/elements/resources.i"
	@echo "... third_party/mutable/elements/resources.s"
	@echo "... third_party/mutable/stmlib/dsp/units.o"
	@echo "... third_party/mutable/stmlib/dsp/units.i"
	@echo "... third_party/mutable/stmlib/dsp/units.s"
	@echo "... third_party/mutable/stmlib/utils/random.o"
	@echo "... third_party/mutable/stmlib/utils/random.i"
	@echo "... third_party/mutable/stmlib/utils/random.s"
	@echo "... tools/synth_demo.o"
	@echo "... tools/synth_demo.i"
	@echo "... tools/synth_demo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

